# Generated by Django 5.1.6 on 2025-02-08 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('power_monitor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electricalparameter',
            name='active_power',
        ),
        migrations.RemoveField(
            model_name='electricalparameter',
            name='apparent_power',
        ),
    ]
